### ISSUE TITLE
   FR1. Registering with State/Driver license ID UI 

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#1]
|FR1. Registering with State/Driver license ID UI|
|---|
|**Goal**: The system should require the customer to sign up using an ID
**Stakeholders:** Customers|
| **Description:** When a customer visits the website for the first time, they will be asked to register as a customer. They will need to enter an email address, phone number, first and last name, a password, and their state/driver license ID number.|
| **Origin:** Based on the initial project specification document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/11/2019|  **Priority:** 1 |

**Comment by White12487** [comment]
You already created the registration pages so, I made you the assigned person for this issue.

**Comment by White12487** [comment]
Allowed for the paths of the applications. User can now register as a customer or restaurant
