### ISSUE TITLE
NFR9.  Accessible on any device

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#10]
|NFR9.  Accessible on any device|
|---|
|**Goal**: The software will be available regardless of what modern device is used
**Stakeholders:** Customers and restaurants|
| **Description:** The website will be able to handle mobile, tablet, and laptop/desktop users. For mobile smartphone users, they will have the option of using an email or a phone number. The other devices will be able to access through a wifi hotspot or wireless connection using an email to log in.
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 1 |

**Comment by OmariKing** [comment]
Can be accessed by mobile device but has slight bug where full page doesn't show up

**Comment by OmariKing** [comment]
Has additional bug of only being able to access Nav bar but only after zooming out and reloading top part of the page

**Comment by OmariKing** [comment]
There are pictures that don't contain css meta data that don't work as well in the mobile access

**Comment by fahmi009** [comment]
That is fine as long as some of it works. After all, this issue is non-functional. Closing issue...........
