### ISSUE TITLE
 NFR10.  Responsive Refresh Time

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#11]
|NFR10.  Responsive Refresh Time|
|---|
|**Goal**:  The data for available restaurants should take at most 10 seconds to refresh
**Stakeholders:** Customers|
| **Description:** The website should be built in a way that allows information from the database to be pulled in seconds to allow the efficient service in providing the location of nearby restaurants offering leftover food.
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 1 |

**Comment by White12487** [comment]
Refresh time is under 10 seconds so, responsive refresh time, check.
