### ISSUE TITLE
FR 15.  Add & Remove food Items(HTML Layout)

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#16]
|FR 15. Restaurant is able to add/remove food that is leftover from a meal to their menu on the app|
|---|
|**Goal**:  To visual to customers about the options available at the restaurant
**Stakeholders:** Resturants|
| **Description:** After every meal is picked up, the restaurant needs to log it into the website and reduce the number of meals available. The same goes if there's an extra meal, and it needs to be added under the restaurant's log. This allows the users to know how many meals are available of a particular dish.
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 1 |

**Comment by White12487** [comment]
able to add food and it is stored in the database under Meals

**Comment by fahmi009** [comment]
The issue is half complete. Moved to Sprint 2.

**Comment by White12487** [comment]
We may need another page. Unless we should have an event where the restaurant owner can request to update their meal availability then we can link them to a form where they can change the meal availability in the database on the same page where they input their meal information.

**Comment by fahmi009** [comment]
Add remove file has the code for that. It works but isn’t connected to the database

**Comment by fahmi009** [comment]
The html page for this is complete as of Nov 24
Database: -----------
