### ISSUE TITLE
FR18.  Passwords and email change 

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#19]
|FR18.  Passwords change |
|---|
|**Goal**: The system should allow users to change password,  and should also have a forget password option
**Stakeholders:** Customers and restaurants|
| **Description:** For personal reasons, users may want to change passwords. So, the system should allow that. However, the system should make sure that State ID, driver’s license ID, and business ID is not being changed. Also, in the log-in screen, an option for forgetting a password should be displayed, which would redirect them to an alternative page to enter the email ID for the account so that a reset password email can be sent. 
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 1 |

**Comment by White12487** [comment]
Can change in the database. Will allow user at a later date possibly

**Comment by fahmi009** [comment]
@OmariKing This issue is not complete. Moving it over to sprint 2.

**Comment by OmariKing** [comment]
Password can be changed for users, Email change not too far from completion
