### ISSUE TITLE
NFR2. Valid Business ID

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#2]
|NFR2.  Require Business ID for SignUp|
|---|
|**Goal**: The System should validate the authenticity of the restaurant
**Stakeholders:** Restaurants
| **Description:** When a restaurant visits our website, they will be directed to a sign-up page. The page will ask, what they want to Sign Up as, a restaurant or a customer. Once the desired option is chosen, they will be asked for their Name, Restaurant email, Restaurant Name, Restaurant's location, business ID, and password. In the case of the business ID, the system should check to see if it is an actual business ID and if the ID matches the name and address provided. If not then the system will display an error message, asking the individual to re-enter the information accurately. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 28/09/2020|  **Priority:** 1 |

**Comment by White12487** [comment]
Having trouble comparing to a public database, may just count the chars and make sure it's not already in the database

**Comment by fahmi009** [comment]
Due to lack of knowledge, we won't be able to implement/connect with the public database to verify EIN.
