### ISSUE TITLE
 NFR20.  Multiple Customers Accessing a Restaurant 

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#21]
| NFR20.  Multiple Customers Accessing a Restaurant |
|---|
|**Goal**: The system will unable to safeguard itself from crushing due to multiple transactions happening at once
**Stakeholders:** Customers|
| **Description:** 
When more than one customer is checking out or accessing one particle restaurant, it is likely that the system, in that case, will crash. The website needs to be built in a way that it can handle the capacity of trying to reach the same goal.
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 1 |

**Comment by OmariKing** [comment]
Public access available for both desktop and mobile access along with time stamps of access

Desktop Web Access
![image](https://user-images.githubusercontent.com/46901954/98276529-1b4aa700-1f64-11eb-813f-bb72f5710d10.png)


Mobile Web Access
![image](https://user-images.githubusercontent.com/46901954/98276411-eb9b9f00-1f63-11eb-85d2-00f0f894a6d2.png)
