### ISSUE TITLE
FR25. About Us

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#22]
|FR25. About Us|
|---|
|**Goal**: The goal is to inform customers about the business
**Stakeholders:** Customers and restaurants|
| **Description:** This option will allow users to learn about the platform. It will explain to the users what the platform is about, what it has to offer, and how they can use it. It will also explain the purpose of the platform to the customers.  |
| **Origin:** Based on the initial project specification document, team members came up with this description during the seventh meeting.|
| **Version:** 1.0  |
|**Date:** 09/11/2019|  **Priority:** 1 |

**Comment by White12487** [comment]
We can all give our input on this page. We should discuss a vision, mission and probably input a mini picture of us or something.

**Comment by White12487** [comment]
Page is done. It's a simple thing to show who we are
