### ISSUE TITLE
FR27. Contact Us Directory

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#27]
|FR27. Contact Us Directory|
|---|
|**Goal**: The goal is to have user feedback stored
**Stakeholders:** Customer and restaurant|
| **Description:** When a customer, restaurant, or visitor, uses the contact us form, the data provided such as name, email, and text from the individual should be stored for future reference. This will allow admin users to contact the individual in regard to the provided feedback if necessary.   |
| **Origin:** Based on the initial project specification document, team members came up with this description during the seventh meeting.|
| **Version:** 1.0  |
|**Date:** 09/11/2019|  **Priority:** 1 |

**Comment by White12487** [comment]
Messages from the contact page are now stored in the database. Under the contactUs model. Displays name, phone #, email and message. It only allows a 4000 character field for the message so we should probably tell the user that on the html page to write in their complaint under 1000 words. We can always increase the max_length though in models.
