### ISSUE TITLE
FR3. Ability to Search for Restaurants Nearby UI

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#3]
|FR1.  Ability to Search for Restaurants Nearby UI |
|---|
|**Goal**: This feature will allow customers to look for nearby restaurants
**Stakeholders:** Customers|
| **Description:** After a customer logs into the system, they will be able to use a search bar and search the system using keywords or names of restaurants. The system will then list the restaurants available within a certain area or radius based on their zip code. 
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 28/09/2020|  **Priority:** 1 |

**Comment by SusannaArun** [comment]
After user enters address, it redirects them to restaurants near them page
