### ISSUE TITLE
FR4. Add Address/Zip code (1 or more) UI

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#4]
|FR4.  Add Address/Zip Code (1 or more)  UI|
|---|
|**Goal**: The system should allow customers to add one or more addresses or zip codes.
**Stakeholders:** Customers|
| **Description:** For a customer to search for a restaurant, they are required to provide a  zipcode or address. Therefore, the system should allow the customer to change or add more addresses. These zip codes or/and addresses should be stored in the customer's directory. If a customer, wishes not to search with their full address, they may also choose to search using a zip code.  
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 1 |

**Comment by SusannaArun** [comment]
made entry for zip code 5 digits limit
