### ISSUE TITLE
NFR5.Authentic login ID

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#5]
|NFR5.Authentic login ID|
|---|
|**Goal**: To allow easy access to the login to a website every time the customer would like to use his/her account
**Stakeholders:** Customers|
| **Description:** The website will save all the login information on a database so that the user has his/her own unique ID to login with. The user will be allowed to log in either using their phone number or email, along with the password they set up during registration. (Licence/state ID number required during the registration process)
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 1 |

**Comment by White12487** [comment]
I need help lol
