### ISSUE TITLE
FR26. User ID Directory

### ISSUE THREAD

**Issue by OmariKing** [WSU-4110/LeftOvr#6]
|FR1.  Internal countdown clock system  UI|
|---|
|**Goal**: System will have a countdown system that counts down from 24 hours.
**Stakeholders:** Customers|
| **Description:** The system will start at 24 hours from the time that the moment the product is confirmed to be picked up so that no other food is order until 24 hours have passed not allowing the user to order another order within that time span. 
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 1 |

**Comment by fahmi009** [comment]
Changed issue name(was a repeated issue). 
And was completed by Dejon for project 1.
