### ISSUE TITLE
FR7.  Leaving Reviews

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#8]
|FR7.  Leaving Reviews|
|---|
|**Goal**: The user should be able to leave reviews for the restaurant
**Stakeholders:** Customers|
| **Description:** Depending on how the experience was for customers, be it going to the restaurant to pick up the leftovers, or the meal itself,  people will be able to see how the employees service was based on how many people ranked it. It gives incentive for restaurants to provide good service through the website and gives people an idea as to how good the food is along with how well they were treated.
--

 | **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 1 |

**Comment by SusannaArun** [comment]
Made individual review pages for each restaurant on sample receipt page
