### ISSUE TITLE
 FR8.  Contact Option

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#9]
|FR8.  Contact Option UI|
|---|
|**Goal**:  If the user is having issues with the application there should be an option for them to contact  anyone on the website for help
**Stakeholders:** Customers|
| **Description:** When a customer is having issues with the application whether it be to check if something is correct within the app or ask for assistance using it, there should be an option on the site to ask someone for help. As long  as the restaurant is still open, someone is available online to help answer questions.
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 1 |

**Comment by White12487** [comment]
Hey, I'm basically going to copy the skeleton of the AboutUs page and rearrange it into a contact form option.

**Comment by White12487** [comment]
Contact page is intact and within the django framework
